language: scala

jdk: oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
   - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
